### ISSUE TITLE
please review recently fix onion transport for libp2p/ipfs

### ISSUE THREAD

**Issue by david415** [whyrusleeping/todo#20]
https://github.com/david415/ipfs-onion-transport
https://github.com/david415/ipfs-onion-transport/blob/master/onion_transport.go

**Comment by whyrusleeping** [comment]
Tests!!!!

**Comment by whyrusleeping** [comment]
LoadKeys should probably happen during construction of the transport.

**Comment by whyrusleeping** [comment]
line 99: probably want to use `io.ReadFull` and check the number of bytes read. `Read` doesnt guarantee you will fill up the buffer (you might not actually read your 825 bytes)

**Comment by whyrusleeping** [comment]
In general, you never want to ignore an error. So definitely try to avoid doing that (always handle them and at minimum log them if youre not planning on returning them).

Aside from that, i'd _love_ to see some unit tests. We really should have a generic test suite that just accepts a Transport object and tests the shit out of it. 

I'm gonna close this as I have now reviewed the code :)

If you need me to do any followup review you won't hurt my feelings at all by opening up another issue (even if it just says do #20 again)
