### ISSUE TITLE
corrections to onion transport and build question

### ISSUE THREAD

**Issue by david415** [whyrusleeping/todo#23]
ok i've made the corrections you specified in the last code review:
https://github.com/david415/ipfs-onion-transport

however i'm having trouble building:
user@subgraph:~/gopath-onion-transport/src/github.com/david415/ipfs-onion-transport$ go test
../../ipfs/go-libp2p-transport/fallback.go:4:2: cannot find package "context" in any of:
    /usr/lib/go-1.6/src/context (from $GOROOT)
    /home/user/gopath-onion-transport/src/context (from $GOPATH)

should i be using some sort of golang module vendoring utility to help with the build?
i noticed your ws transport repo has got one of these:
https://github.com/whyrusleeping/ws-transport/blob/master/package.json

**Comment by whyrusleeping** [comment]
@david415 Looks like you need to update to go1.7. 

Sorry for the delay, was in china. Close if that resolves the issue or this is no longer relevant
