### ISSUE TITLE
Input on go-ipfs pubsub issue

### ISSUE THREAD

**Issue by haadcode** [whyrusleeping/todo#32]
Hey, need your input (and somewhat of a decision) on https://github.com/ipfs/js-ipfs-api/pull/493#issuecomment-289025337. Basically: is it something we should fix or are we good to ship? If you need any more details and info, let us know the issue.

**Comment by whyrusleeping** [comment]
Gave feedback, Floodsub messages are not guaranteed to be in order. Please reopen this if you need more feedback
