### ISSUE TITLE
help: fs-repo-migrations: sharness/dependencies: update ipfs-update

### ISSUE THREAD

**Issue by chriscool** [whyrusleeping/todo#4]
Hi Jeromy,

Could you take a look at what is wrong:

https://github.com/ipfs/fs-repo-migrations/pull/25

Thanks!

**Comment by whyrusleeping** [comment]
suggested pushing a branch to the repo so I can edit it and fix the godeps issues. Reopen when I need to take a look again

**Comment by chriscool** [comment]
Branch https://github.com/ipfs/fs-repo-migrations/tree/update-ipfs-update pushed!

**Comment by chriscool** [comment]
It looks like I cannot reopen though...
